name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install
        run: npm ci

      - name: Create sitemap.xml
        run: LASTMOD=`date "+%Y-%m-%dT%H:%M:%SZ"` envsubst < sitemap.template.xml > public/sitemap.xml

      - name: Show sitemap.xml
        run: cat public/sitemap.xml

      - run: ls public

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
